migrate(
  (app) => {
    app.importCollections(
      [
        {
          id: "cvprofile001abc",
          name: "cv_profiles",
          type: "base",
          listRule: "",
          viewRule: "",
          createRule: null,
          updateRule: null,
          deleteRule: null,
          fields: [
            {
              id: "text3208210256",
              name: "id",
              type: "text",
              system: true,
              required: true,
              primaryKey: true,
              presentable: false,
              hidden: false,
              min: 15,
              max: 15,
              pattern: "^[a-z0-9]+$",
              autogeneratePattern: "[a-z0-9]{15}",
            },
            {
              id: "text2560465762",
              name: "slug",
              type: "text",
              system: false,
              required: true,
              primaryKey: false,
              presentable: false,
              hidden: false,
              min: 0,
              max: 0,
              pattern: "",
              autogeneratePattern: "",
            },
            {
              id: "text1579384326",
              name: "name",
              type: "text",
              system: false,
              required: true,
              primaryKey: false,
              presentable: false,
              hidden: false,
              min: 0,
              max: 0,
              pattern: "",
              autogeneratePattern: "",
            },
            {
              id: "select2539659139",
              name: "template",
              type: "select",
              system: false,
              required: true,
              presentable: false,
              hidden: false,
              maxSelect: 1,
              values: ["classic", "modern", "minimal"],
            },
            {
              id: "bool4116874775",
              name: "is_default",
              type: "bool",
              system: false,
              required: false,
              presentable: false,
              hidden: false,
            },
            {
              id: "file1269934601",
              name: "profile_picture",
              type: "file",
              system: false,
              required: false,
              presentable: false,
              hidden: false,
              maxSelect: 1,
              maxSize: 0,
              mimeTypes: null,
              protected: false,
              thumbs: null,
            },
            {
              id: "file1269934602",
              name: "cover_picture",
              type: "file",
              system: false,
              required: false,
              presentable: false,
              hidden: false,
              maxSelect: 1,
              maxSize: 0,
              mimeTypes: null,
              protected: false,
              thumbs: null,
            },
          ],
          indexes: [],
        },
      ],
      false,
    );
  },
  (app) => {
    app.importCollections(
      [
        {
          id: "cvprofile001abc",
          name: "cv_profiles",
          type: "base",
          listRule: "",
          viewRule: "",
          createRule: null,
          updateRule: null,
          deleteRule: null,
          fields: [
            {
              id: "text3208210256",
              name: "id",
              type: "text",
              system: true,
              required: true,
              primaryKey: true,
              presentable: false,
              hidden: false,
              min: 15,
              max: 15,
              pattern: "^[a-z0-9]+$",
              autogeneratePattern: "[a-z0-9]{15}",
            },
            {
              id: "text2560465762",
              name: "slug",
              type: "text",
              system: false,
              required: true,
              primaryKey: false,
              presentable: false,
              hidden: false,
              min: 0,
              max: 0,
              pattern: "",
              autogeneratePattern: "",
            },
            {
              id: "text1579384326",
              name: "name",
              type: "text",
              system: false,
              required: true,
              primaryKey: false,
              presentable: false,
              hidden: false,
              min: 0,
              max: 0,
              pattern: "",
              autogeneratePattern: "",
            },
            {
              id: "select2539659139",
              name: "template",
              type: "select",
              system: false,
              required: true,
              presentable: false,
              hidden: false,
              maxSelect: 1,
              values: ["classic", "modern", "minimal"],
            },
            {
              id: "bool4116874775",
              name: "is_default",
              type: "bool",
              system: false,
              required: false,
              presentable: false,
              hidden: false,
            },
          ],
          indexes: [],
        },
      ],
      false,
    );
  },
);
